# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j6lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000059.tlbin:system/app/mcRegistry/ffffffff000000000000000000000059.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000060.tlbin:system/app/mcRegistry/ffffffff000000000000000000000060.tlbin \
    vendor/samsung/j6lte/proprietary/app/mcRegistry/ffffffff000000000000000000000077.tlbin:system/app/mcRegistry/ffffffff000000000000000000000077.tlbin \
    vendor/samsung/j6lte/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/j6lte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/j6lte/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/j6lte/proprietary/lib/libHpr_RecFace_dl_v1.0.so:system/lib/libHpr_RecFace_dl_v1.0.so \
    vendor/samsung/j6lte/proprietary/lib/libHpr_RecGAE_cvFeature_v1.0.so:system/lib/libHpr_RecGAE_cvFeature_v1.0.so \
    vendor/samsung/j6lte/proprietary/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so:system/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so \
    vendor/samsung/j6lte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/j6lte/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/samsung/j6lte/proprietary/lib/libprotobuf-cpp-full-rtti.so:system/lib/libprotobuf-cpp-full-rtti.so \
    vendor/samsung/j6lte/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/j6lte/proprietary/lib/libprotobuf-cpp-lite.so:system/lib/libprotobuf-cpp-lite.so \
    vendor/samsung/j6lte/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/j6lte/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/j6lte/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/samsung/j6lte/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000073.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000073.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000062.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000062.tlbin \
    vendor/samsung/j6lte/proprietary/vendor/bin/hw/gpsd:system/vendor/bin/hw/gpsd \
    vendor/samsung/j6lte/proprietary/vendor/etc/gnss/ca.pem:system/vendor/etc/gnss/ca.pem \
    vendor/samsung/j6lte/proprietary/vendor/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin \
    vendor/samsung/j6lte/proprietary/vendor/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin \
    vendor/samsung/j6lte/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/j6lte/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/j6lte/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/j6lte/proprietary/vendor/etc/wifi/cred.conf:system/vendor/etc/wifi/cred.conf \
    vendor/samsung/j6lte/proprietary/vendor/etc/wifi/nvram.txt_36:system/vendor/etc/wifi/nvram.txt_36 \
    vendor/samsung/j6lte/proprietary/vendor/firmware/bcm43436B0_V0070.0091.hcd:system/vendor/firmware/bcm43436B0_V0070.0091.hcd \
    vendor/samsung/j6lte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/j6lte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/j6lte/proprietary/vendor/firmware/setfile_3l2.bin:system/vendor/firmware/setfile_3l2.bin \
    vendor/samsung/j6lte/proprietary/vendor/firmware/setfile_4h5yc.bin:system/vendor/firmware/setfile_4h5yc.bin \
    vendor/samsung/j6lte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/hw/camera.vendor.exynos7870.so:system/vendor/lib/hw/camera.vendor.exynos7870.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/hw/gralloc.exynos5.so:system/vendor/lib/hw/gralloc.exynos5.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/hw/sensors.universal7870.so:system/vendor/lib/hw/sensors.universal7870.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libHpr_LocFace_mvfd_v1.0.so:system/vendor/lib/libHpr_LocFace_mvfd_v1.0.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so:system/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so \
    vendor/samsung/j6lte/proprietary/lib/libOpenCv.so:system/lib/libOpenCv.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libSEF.so:system/vendor/lib/libSEF.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libaudio-ril.so:system/vendor/lib/libaudio-ril.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libcsc.so:system/vendor/lib/libcsc.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynoscamera.so:system/vendor/lib/libexynoscamera.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynosgscaler.so:system/vendor/lib/libexynosgscaler.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynosscaler.so:system/vendor/lib/libexynosscaler.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynosutils.so:system/vendor/lib/libexynosutils.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libexynosv4l2.so:system/vendor/lib/libexynosv4l2.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libhwjpeg.so:system/vendor/lib/libhwjpeg.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libsecril-client.so:system/vendor/lib/libsecril-client.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libsensorlistener.so:system/vendor/lib/libsensorlistener.so \
    vendor/samsung/j6lte/proprietary/lib/libsomp.so:system/lib/libsomp.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libstainkiller.so:system/vendor/lib/libstainkiller.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/vendor/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/j6lte/proprietary/vendor/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/vendor/lib/omx/libOMX.Exynos.WMV.Decoder.so
